version: '3.6'
services:
  api:
    image: unchained-local-go
    environment:
      - GOCACHE=/tmp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fury-api.rule=Host(`api.fury.localhost`)'
      - 'traefik.http.services.fury-api.loadbalancer.server.port=3000'
    command: ["-r", "(pkg|internal|fury)", "-R", "swagger", "--", "sh", "-c", "swagger generate spec -w coinstacks/fury -o coinstacks/fury/api/swagger.json -x protoc-gen-openapiv2 -m && go run cmd/fury/main.go -env cmd/fury/.env"]
    working_dir: /app
    volumes:
      - ../..:/app
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
